services:
  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: ge-svi-ecommerce
      JWT_SECRET: super_secret
      RABBITMQ_URI: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      RABBITMQ_QUEUE: EMAIL
      SWAGGER_TITLE: "GE SVI Ecommerce API"
      SWAGGER_DESCRIPTION: "API documentation for GE SVI Ecommerce"
      SWAGGER_APP_VERSION: 1.0.0
      PORT: 3000
      IP: 0.0.0.0
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./src:/usr/src/app/src
    command: bash -c "yarn run migration:run && yarn run start"

  # Microservice
  microservice:
    build:
      context: .
      dockerfile: microservice/Dockerfile
    container_name: nest-microservice
    environment:
      RABBITMQ_URI: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      RABBITMQ_QUEUE: EMAIL
    depends_on:
      - rabbitmq
    volumes:
      - ./microservice:/usr/src/app/microservice
    command: yarn run start:microservice

  # PostgreSQL service
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ge-svi-ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # pgAdmin service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_USER: rabbitmq
      RABBITMQ_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  pgdata:
  rabbitmq_data: